### ISSUE TITLE
LID Type Rain Barrel - changing flow coefficient

### ISSUE THREAD

**Issue by MartinOberascher** [jennwuu/pyswmm#1]
Hi,

many thanks to your efforts for pyswmm with LID features.

Currently, I am testing the LID Type "Rain Barrel" trying to change settings during the simulation. 

When I want to change the flow coefficient during the simulation, the storage level inside the Rain Barrel is set to 0. This problem can be seen in the example in the appendix (in the example I change the drain coefficent at 6pm, and the storage level falls from 662mm to 0mm during one time step).

[SWMM-Report_RB.txt](https://github.com/jennwuu/pyswmm/files/3289430/SWMM-Report_RB.txt)
[Test_RB.py.txt](https://github.com/jennwuu/pyswmm/files/3289457/Test_RB.py.txt)
[Test_rain.dat.txt](https://github.com/jennwuu/pyswmm/files/3289458/Test_rain.dat.txt)
[Test_RB.inp.txt](https://github.com/jennwuu/pyswmm/files/3289460/Test_RB.inp.txt)

This problem should have arisen in the last changes. Before that I used a version from December 2018 in which the calculation worked perfectly.

Thanks!

**Comment by jennwuu** [comment]
Hi @MartinOberascher,

Thanks for identifying this issue. I think it is caused by this new function: https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/blob/4baa02867556ad2f364f927836c693c4c1511406/src/toolkitAPI.c#L1515. I will look into.
In the meantime, I will migrate this issue to OWA/pyswmm. 
Thanks!

**Comment by jennwuu** [comment]
@MartinOberascher I updated pyswmm code. There are now limited parameters that can be changed during model simulation (only mostly drain layer parameters) due to potential routing concerns. 

The storage depth no longer resets to zero when you update the drain coefficient.

**Comment by MartinOberascher** [comment]
**@jennwuu** Now it works, thank you for solving it!

In the meantime I have further tested the LID functions. I have another question about @drain_node.setter and @drain_subcatchment.setter: there are two self._model.setLidUOption(...) functions in them. It seems that the second function exceeds the first function and "Drain to" is always set to -1 (same drain node like subcatchment). If I comment out the second function I can change the "Drain to" to any node/subcatchment i want. Is this also because of the routing problems you mentioned?

Thanks!

**Comment by jennwuu** [comment]
Hi @MartinOberascher, 

Thanks for continuing to test the lid pyswmm! 
There are two function calls to self._model.setLidUOption because the lid unit can only drain to subcatchment or node. 

In the drain_subcatchment.setter, the first function call of setLidUOption(...) is to change the subcatchment index to according to what the user specified.
The second function call of setLidUOption(...) is to update the node index to -1 to indicate that the lid is no longer draining to the node it was previously specified. 
https://github.com/jennwuu/pyswmm/blob/8914d37a846b30ba383e04ea22765cf053b25444/pyswmm/lidgroups.py#L371-L389

For drain_node.setter, the set up is the same:
https://github.com/jennwuu/pyswmm/blob/8914d37a846b30ba383e04ea22765cf053b25444/pyswmm/lidgroups.py#L403-L421
The first function call of setLidUOption(...) update the lid to drain to node as specified by user.
The second function call of setLidUOption(...) is update that the lid unit is no longer draining to the subcatchment.

Not sure if I was able to answer your question, but I am open to suggestion. In general, I am hesitant to avail setters through the api due to potential routing concerns.

**Comment by MartinOberascher** [comment]
Hi @jennwuu 

A better description of the problem is the interaction of lidgroups.py and toolkitAPI.c.

For example, calling @drain_node.setter https://github.com/jennwuu/pyswmm/blob/8914d37a846b30ba383e04ea22765cf053b25444/pyswmm/lidgroups.py#L403-L421
executes first this function: 
https://github.com/jennwuu/Stormwater-Management-Model/blob/ec28f3dce7af1a964cb1604d7b5125e68f954b6a/src/toolkitAPI.c#L1059-L1062
(setting drain to node as specified by user and set subcatchment index to -1).
and then this function:
https://github.com/jennwuu/Stormwater-Management-Model/blob/ec28f3dce7af1a964cb1604d7b5125e68f954b6a/src/toolkitAPI.c#L1055-L1058
(setting first subcatchment index to -1 and drain to node to -1).

Whereby at the end the drain to node and subcatchment index are always set to -1 and no changes are made to these parameters. 
For the @drain_subcathment_setter it is the same.

**Comment by jennwuu** [comment]
@MartinOberascher 

Wow, good catch! You're correct. Thanks for spotting this error. If that is the case, I should remove the second function as you mentioned earlier.

Thank you! I really appreciate all your help!
